# -*- coding: utf-8 -*-
"""EDA for Covid 19 state -wise data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dUOztgmvijSWstBbtlowpIqsFYi4WgYc
"""

import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("/content/Latest Covid-19 India Status.csv")

df.columns

df.isnull().sum()

df.duplicated().sum()

df.shape

df

"""Plot for top 10 states with highest Death Ratio"""

top_states = df.nlargest(10, "Death Ratio")
top_states

plt.figure(figsize=(15,6))
plt.title('Top 10 States with highest Death ratio')
plt.xlabel('State/UTs')
plt.ylabel('Death Ratio')
sns.barplot(x='State/UTs', y='Death Ratio', data=top_states)
plt.show()

top_states_discharge = df.nlargest(10, "Discharge Ratio")
top_states_discharge

plt.figure(figsize=(20,6))
plt.title('Top 10 States with highest Discharge ratio')
plt.xlabel('State/UTs')
plt.ylabel('Discharge Ratio')
sns.barplot(x='State/UTs', y='Discharge Ratio', data=top_states_discharge)
plt.show()

top_states_active = df.nlargest(10, "Active Ratio")
top_states_active

plt.figure(figsize=(20,6))
plt.title('Top 10 States with highest Active ratio')
plt.xlabel('State/UTs')
plt.ylabel('Active Ratio')
sns.barplot(x='State/UTs', y='Death Ratio', data=top_states_active)
plt.show()

sns.displot(df['Total Cases'] , kde = True)

sns.displot(df['Deaths'] , color = 'red', kde = True)

sns.displot(df['Discharged'] , color = 'orange', kde = True)

sns.displot(df['Population'] , color = 'red', kde = True)

df.corr()

sns.heatmap(df.corr())

sns.pairplot(df)

sns.scatterplot(x='Population', y='Deaths', data=df)
plt.title('Scatter Plot with Regression Line')
plt.show()

sns.scatterplot(x='Population', y='Discharged', data=df)
plt.title('Scatter Plot with Regression Line')
plt.show()

sns.scatterplot(x='Population', y='Active', data=df)
plt.title('Scatter Plot with Regression Line')
plt.show()